# 74.71 ± 1.42   # ScaleNet: 74.94 +- 2.13
squirrel:
  lr: 0.01
  hidden_dim: 128
  num_layers: 4
  jk: "max"
  patience: 400
  conv_type: "dir-gcn"
  alpha: 1
  normalize: True
  beta: 1
  gama: 1

# 79.71 ± 1.26  # ScaleNet:79.95 +- 1.4
chameleon:
  lr: 0.005
  hidden_dim: 128
  num_layers: 5
  jk: "max"
  patience: 400
  conv_type: "dir-gcn"
  alpha: 1
  normalize: True
  beta: 1
  gama: 1

# 64.08 ± 0.26
arxiv-year:
  lr: 0.005
  hidden_dim: 256
  num_layers: 6
  jk: "cat"
  patience: 200
  conv_type: "dir-gcn"
  beta: 0.5
#  gama: 0.5

# 73.95 ± 0.05
snap-patents:
  lr: 0.01
  hidden_dim: 32
  num_layers: 5
  jk: "max"
  patience: 200
  normalize: True
  conv_type: "dir-gcn"
  beta: 0.5
#  gama: 0.5


# 91.23 ± 0.32
directed-roman-empire:
  lr: 0.01
  hidden_dim: 256
  num_layers: 5
  jk: "cat"
  dropout: 0.2
  patience: 200
  conv_type: "dir-sage"
  beta: 0.5
#  gama: 0.5

#hyperparameter unsure
ogbn-arxiv:
  lr: 0.005
  hidden_dim: 256
  num_layers: 6
  jk: "cat"
  patience: 200
  conv_type: "dir-gcn"
  beta: 0.5
#  gama: 0.5

